# Generated by Django 5.2.5 on 2025-09-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create a book'), ('can_delete', 'Can delete a book')]},
        ),
    ]
